apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bckst
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bckst 
  name: bckst
  namespace: test
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: bckst 
